name: Test
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: npm install

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint
